"use client";
import { useState } from 'react';
import { Title } from 'react-admin';
import { Alert,Box,Button,Card,CardContent,Chip,Dialog,DialogActions,DialogContent,DialogTitle,FormControlLabel,Stack,Switch,TextField,Typography } from '@mui/material';
import { useCatalog } from './ProjectCatalog';
import { api } from './dataProvider';
import { projectPath,type ProjectSummary } from '@/lib/projects';
export default function Projects(){
 const {projects,reload}=useCatalog();const [adding,setAdding]=useState(false);const [repositoryUrl,setRepositoryUrl]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [removed,setRemoved]=useState(false);const [confirm,setConfirm]=useState<ProjectSummary>();const [notice,setNotice]=useState('');
 const run=async(work:()=>Promise<void>)=>{setBusy(true);setError('');try{await work();await reload();}catch(e){setError((e as Error).message);await reload().catch(()=>{});}finally{setBusy(false);}};
 const update=(p:ProjectSummary,body:unknown)=>run(async()=>{await api(`/api/projects/${p.id}`,'PUT',body);});
 const add=()=>run(async()=>{const {data}=await api('/api/projects','POST',{repositoryUrl});setAdding(false);setRepositoryUrl('');if(data.archivedAt){setRemoved(true);setNotice('This project was previously removed. Restore it below to keep its existing articles and settings.');}else{window.location.hash=`${projectPath(data.id)}/settings`;}});
 return <Box p={{xs:2,md:4}}><Title title="Projects"/><Stack direction="row" justifyContent="space-between" alignItems="center" gap={2}><Typography variant="h3">Projects</Typography><Button variant="contained" disabled={busy} onClick={()=>{setError('');setAdding(true);}}>Add project</Button></Stack>
 <Typography color="text.secondary" mt={1} mb={3}>Connect a GitHub website, review its setup once, and manage its blog automatically.</Typography>
 {error&&!adding&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}{notice&&<Alert severity="info" sx={{mb:2}}>{notice}</Alert>}
 <FormControlLabel control={<Switch checked={removed} onChange={e=>setRemoved(e.target.checked)}/>} label="Show removed projects"/>
 <Stack spacing={2}>{projects.filter(p=>removed?Boolean(p.archivedAt):!p.archivedAt).map(p=><Card key={p.id}><CardContent sx={{p:3}}><Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" gap={2}><Box><Typography variant="h5">{p.name}</Typography><Typography color="text.secondary" mt={1}>{p.description}</Typography><Typography variant="body2" mt={1}>{p.repository}</Typography></Box><Chip label={p.archivedAt?'Removed':p.localOnly?'Local test project':p.setup&&!p.setup.compatible?'Blog integration needed':p.setup&&!p.setup.reviewed?'Review setup':p.automationEnabled?'Automatic blog on':'Automatic blog off'}/></Stack>
 {!p.archivedAt?<><FormControlLabel sx={{mt:2}} control={<Switch checked={p.automationEnabled} disabled={busy||p.localOnly||Boolean(p.setup&&(!p.setup.compatible||!p.setup.reviewed))} onChange={e=>update(p,{action:'automation',enabled:e.target.checked})}/>} label="Automatic blog creation and publication"/><Typography variant="body2" color="text.secondary">Turning this off pauses scheduled creation and publication. Existing articles stay available. Manual actions remain available.</Typography><Stack direction="row" gap={2} mt={2}><Button variant="contained" href={`#${projectPath(p.id,p.setup&&!p.setup.reviewed?'settings':'')}`}>Open project</Button><Button color="error" disabled={busy} onClick={()=>setConfirm(p)}>Remove project</Button></Stack></>:<Button sx={{mt:2}} disabled={busy} onClick={()=>update(p,{action:'restore'})}>Restore project (automation stays off)</Button>}
 </CardContent></Card>)}</Stack>
 <Dialog open={adding} onClose={()=>{if(!busy)setAdding(false);}} fullWidth maxWidth="sm"><DialogTitle>Add a project from GitHub</DialogTitle><DialogContent><Typography mb={2}>Paste the repository link. We will read selected website files, suggest the project profile with OpenAI, and check blog compatibility. No repository code is executed or changed. Automatic publishing starts off.</Typography><TextField label="GitHub repository URL" placeholder="https://github.com/owner/website" fullWidth value={repositoryUrl} onChange={e=>setRepositoryUrl(e.target.value)} disabled={busy}/><Typography variant="body2" color="text.secondary" mt={2}>Public repositories can be analyzed immediately. Private repositories require GitHub access to be configured first. AI profile analysis is a paid API request.</Typography>{busy&&<Alert severity="info" sx={{mt:2}}>Reading the repository and preparing setup. This can take a few minutes.</Alert>}{error&&<Alert severity="error" sx={{mt:2}}>{error}</Alert>}</DialogContent><DialogActions><Button disabled={busy} onClick={()=>setAdding(false)}>Cancel</Button><Button variant="contained" disabled={busy||!repositoryUrl.trim()} onClick={add}>{busy?'Analyzing…':'Analyze and add project'}</Button></DialogActions></Dialog>
 <Dialog open={Boolean(confirm)} onClose={()=>{if(!busy)setConfirm(undefined);}}><DialogTitle>Remove {confirm?.name} from the admin?</DialogTitle><DialogContent>This pauses automatic creation and publication and hides the project. Its articles, history and settings are kept for restoration. The GitHub repository and live website are not deleted. A publication already sent to GitHub may still finish.</DialogContent><DialogActions><Button disabled={busy} onClick={()=>setConfirm(undefined)}>Cancel</Button><Button color="error" disabled={busy} onClick={()=>run(async()=>{await api(`/api/projects/${confirm!.id}`,'PUT',{action:'archive'});setConfirm(undefined);})}>Remove project</Button></DialogActions></Dialog>
 </Box>;
}
